name: Publish to NPM
on:
    push:
        tags:
            - '*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
            - name: Cache node_modules
              id: cache-modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

            - name: Install
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: npm install

            - run: npm run build

            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
    release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: gcal2ics ${{ github.ref }}
                  draft: false
                  prerelease: false
